# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

# Пользователи
## Регистрация пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack.Torrance",
  "email": "torans@overlook.net",
  "password": "1234abcd",
  "avatar": "torrance.png",
  "userType": "pro"
}

###

## Регистрация пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack.Torrance2",
  "email": "torans2@overlook.net",
  "password": "1234abcd",
  "avatarPath": "avatar-605331.jpg",
  "userType": "pro"
}


### Регистрация пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack.Torrance3",
  "email": "torans3@overlook.net",
  "password": "1234abcd",
  "avatarPath": "avatar-605331.jpg",
  "userType": "pro"
}

###

# Login user
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans3@overlook.net",
  "password": "1234abcd"
}

###

## Авторизация пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "123456"
}

###

# Check user
GET http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczNAb3Zlcmxvb2submV0IiwiaWQiOiI2MmIxNzlmYjc5MzQ1OWNhNTk5MGNhMDciLCJpYXQiOjE2NTU3OTg1NDUsImV4cCI6MTY1NTk3MTM0NX0.5wsEWlzivXWu-u5f2Vnd1xJaGbYqMQFa5rT2fEMsU38


###

## Отправка аватарки пользователю

POST http://localhost:4000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="an.png"
Content-Type: image/png

< /!/go/an.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Отправка аватарки пользователю

POST http://localhost:4000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="an.svg"
Content-Type: image/svg

< /!/java/cable.svg

------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
# ПРЕДЛОЖЕНИЯ
# Create offer
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczNAb3Zlcmxvb2submV0IiwiaWQiOiI2MmIxNzlmYjc5MzQ1OWNhNTk5MGNhMDciLCJpYXQiOjE2NTU3OTg1NDUsImV4cCI6MTY1NTk3MTM0NX0.5wsEWlzivXWu-u5f2Vnd1xJaGbYqMQFa5rT2fEMsU38

{
  "title": "000 2222 222222",
  "description": "222 Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.",
  "postDate": "2022-05-05T09:04:41.515Z",
  "city": {
    "name": "Amsterdam",
    "location": {
      "latitude": 52,
      "longitude": 4
    }
  },
  "previewImage": "hotel5.jpg",
  "images": [
    "hotel51.jpg",
    "hotel52.jpg",
    "hotel53.jpg",
    "hotel54.jpg",
    "hotel55.jpg",
    "hotel56.jpg"
  ],
  "isPremium": false,
  "rating": 4,
  "type": "room",
  "rooms": 7,
  "maxAdults": 7,
  "price": 91935,
  "goods": [
    "Air conditioning",
    "Fridge",
    "Washer",
    "Towels"
  ],
  "countComments": 1,
  "location": {
    "latitude": 52,
    "longitude": 4
  }
}

###
# Update offer
PUT http://localhost:4000/offers/62a1900b1a068de51bd8a34c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI

{
  "title": "333 2222 222222",
  "description": "222 Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.",
  "postDate": "2022-05-05T09:04:41.515Z",
  "city": {
    "name": "Amsterdam",
    "location": {
      "latitude": 52,
      "longitude": 4
    }
  },
  "previewImage": "hotel5.jpg",
  "images": [
    "hotel51.jpg",
    "hotel52.jpg",
    "hotel53.jpg",
    "hotel54.jpg",
    "hotel55.jpg",
    "hotel56.jpg"
  ],
  "isPremium": false,
  "rating": 4,
  "type": "room",
  "rooms": 7,
  "maxAdults": 7,
  "price": 91935,
  "goods": [
    "Air conditioning",
    "Fridge",
    "Washer",
    "Towels"
  ],
  "author": "629dbdc5745ee4203c2f2c93",
  "countComments": 1,
  "location": {
    "latitude": 52,
    "longitude": 4
  }
}

###

# Delete offer
DELETE http://localhost:4000/offers/627b812d07347a02bbf47a44 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczJAb3Zlcmxvb2submV0IiwiaWQiOiI2MmFhZTU3Y2FiYTA4ZjU1NTQwM2JlMzYiLCJpYXQiOjE2NTU0NTE2NTcsImV4cCI6MTY1NTYyNDQ1N30.iKg5P0O0p_1jKRJ_pHL4NOSwFL-ihIcCao8xx3dw3RE

###
# Get offers
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###
## getOneOffer

GET http://localhost:4000/offers/62a1900b1a068de51bd8a34c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI

###

###
## getPremiumOffers

GET http://localhost:4000/offers/premium HTTP/1.1
Content-Type: application/json
###

###
# КОММЕНТАРИИ
# Get comments
GET http://localhost:4000/offers/62b2da7fe507a241600291cc/comments HTTP/1.1
Content-Type: application/json

###

# Create comment
POST http://localhost:4000/offers/62ac48f99abde4d036d7a316/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczJAb3Zlcmxvb2submV0IiwiaWQiOiI2MmFhZTU3Y2FiYTA4ZjU1NTQwM2JlMzYiLCJpYXQiOjE2NTU0NTE2NTcsImV4cCI6MTY1NTYyNDQ1N30.iKg5P0O0p_1jKRJ_pHL4NOSwFL-ihIcCao8xx3dw3RE

{
  "text": "88888 klhkh h lkhljl; l;kjlkjl lkj lj",
  "rating": 5
}

### Запрос комментариев к предложению
GET http://localhost:4000/offers/62a1900b1a068de51bd8a34c/comments
Accept: application/json

### Set favorite status
POST http://localhost:4000/offers/favorites/627b812d07347a02bbf47a49/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI


### Set favorite status
POST http://localhost:4000/offers/favorites/627b812d07347a02bbf47a49/0 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI


### Get favorite offers
GET http://localhost:4000/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI

