# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

# Пользователи
## Регистрация пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack.Torrance",
  "email": "torans@overlook.net",
  "password": "1234abcd",
  "avatar": "torrance.png",
  "userType": "pro"
}

###

# Login user
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "oifylsdf"
}

###

## Авторизация пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "123456"
}

###

## Отправка аватарки пользователю

POST http://localhost:4000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="an.png"
Content-Type: image/png

< /!/go/woman.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Отправка аватарки пользователю

POST http://localhost:4000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="an.svg"
Content-Type: image/svg

< /!/java/cable.svg

------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
# ПРЕДЛОЖЕНИЯ
# Create offer
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "444 2222 222222",
  "description": "222 Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.",
  "postDate": "2022-05-05T09:04:41.515Z",
  "city": {
    "name": "Amsterdam",
    "location": {
      "latitude": 52,
      "longitude": 4
    }
  },
  "previewImage": "hotel5.jpg",
  "images": [
    "hotel51.jpg",
    "hotel52.jpg",
    "hotel53.jpg",
    "hotel54.jpg",
    "hotel55.jpg",
    "hotel56.jpg"
  ],
  "isPremium": false,
  "rating": 4,
  "type": "room",
  "rooms": 7,
  "maxAdults": 7,
  "price": 91935,
  "goods": [
    "Air conditioning",
    "Fridge",
    "Washer",
    "Towels"
  ],
  "author": "629dbdc5745ee4203c2f2c93",
  "countComments": 1,
  "location": {
    "latitude": 52,
    "longitude": 4
  }
}

###
# Update offer
PUT http://localhost:4000/offers/629dbfa4d4f58faa59f5e849 HTTP/1.1
Content-Type: application/json

{
  "title": "333 2222 222222",
  "description": "222 Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.",
  "postDate": "2022-05-05T09:04:41.515Z",
  "city": {
    "name": "Amsterdam",
    "location": {
      "latitude": 52,
      "longitude": 4
    }
  },
  "previewImage": "hotel5.jpg",
  "images": [
    "hotel51.jpg",
    "hotel52.jpg",
    "hotel53.jpg",
    "hotel54.jpg",
    "hotel55.jpg",
    "hotel56.jpg"
  ],
  "isPremium": false,
  "rating": 4,
  "type": "room",
  "rooms": 7,
  "maxAdults": 7,
  "price": 91935,
  "goods": [
    "Air conditioning",
    "Fridge",
    "Washer",
    "Towels"
  ],
  "author": "629dbdc5745ee4203c2f2c93",
  "countComments": 1,
  "location": {
    "latitude": 52,
    "longitude": 4
  }
}

###

# Delete offer
DELETE http://localhost:4000/offers/629dbfa4d4f58faa59f5e849 HTTP/1.1
Content-Type: application/json

###
# Get offers
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###
## getOneOffer

GET http://localhost:4000/offers/62a1900b1a068de51bd8a34c HTTP/1.1
Content-Type: application/json
###

###
## getPremiumOffers

GET http://localhost:4000/offers/premium HTTP/1.1
Content-Type: application/json
###

###
# КОММЕНТАРИИ
# Get comments
GET http://localhost:4000/offers/627b80b930e4a5aa5a5a4cab/comments HTTP/1.1
Content-Type: application/json

###

# Create comment
POST http://localhost:4000/offers/62a1900b1a068de51bd8a34c/comments HTTP/1.1
Content-Type: application/json

{
  "text": "3333 klhkh h lkhljl; l;kjlkjl lkj lj",
  "rating": 3
}

### Запрос комментариев к предложению
GET http://localhost:4000/offers/62a1900b1a068de51bd8a34c/comments
Accept: application/json

### Set favorite status
POST http://localhost:4000/offers/favorites/627b812d07347a02bbf47a44/1 HTTP/1.1
Content-Type: application/json

### Set favorite status
POST http://localhost:4000/offers/favorites/627b812d07347a02bbf47a49/1 HTTP/1.1
Content-Type: application/json

### Get favorite offers
GET http://localhost:4000/offers/favorites HTTP/1.1
Content-Type: application/json
