### Регистрация нового пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack.Torrance5",
  "email": "torans5@overlook.net",
  "password": "jhgjgjk",
  "avatarPath": "avatar-605331.jpg",
  "userType": "pro"
}


### Авторизация пользователя
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans5@overlook.net",
  "password": "jhgjgjk"
}


### Проверка пользователя
GET http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczVAb3Zlcmxvb2submV0IiwiaWQiOiI2MmJhOTdjYjFiZjZkMTBjZjk5NjlhMTMiLCJpYXQiOjE2NTYzOTU3NDksImV4cCI6MTY1NjU2ODU0OX0.RrKbdgOmefCZpWDxXiguebJwqqNgZ5m6TWh9Ljmtj1A


### Отправка аватарки пользователя
POST http://localhost:4000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="an.png"
Content-Type: image/png

< /!/go/an.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Создание нового предложения
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczRAb3Zlcmxvb2submV0IiwiaWQiOiI2MmJhOTNjZDQ1ZDhlMGY0NmQ5YzMwZjMiLCJpYXQiOjE2NTYzOTQ3MzAsImV4cCI6MTY1NjU2NzUzMH0.JZvaXkRdEVAW6Fj6ODeTD5S8KdQyeknwZUiyc8KZCVo

{
  "title": "111 2222 222222",
  "description": "222 Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.",
  "postDate": "2022-05-05T09:04:41.515Z",
  "city": {
    "name": "Amsterdam",
    "location": {
      "latitude": 52,
      "longitude": 4
    }
  },
  "previewImage": "hotel5.jpg",
  "images": [
    "hotel51.jpg",
    "hotel52.jpg",
    "hotel53.jpg",
    "hotel54.jpg",
    "hotel55.jpg",
    "hotel56.jpg"
  ],
  "isPremium": false,
  "rating": 4,
  "type": "room",
  "rooms": 7,
  "maxAdults": 7,
  "price": 91935,
  "goods": [
    "Air conditioning",
    "Fridge",
    "Washer",
    "Towels"
  ],
  "countComments": 1,
  "location": {
    "latitude": 52,
    "longitude": 4
  }
}


### Обновление существующего предложения
PUT http://localhost:4000/offers/62a1900b1a068de51bd8a34c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI

{
  "title": "333 2222 222222",
  "description": "222 Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.",
  "postDate": "2022-05-05T09:04:41.515Z",
  "city": {
    "name": "Amsterdam",
    "location": {
      "latitude": 52,
      "longitude": 4
    }
  },
  "previewImage": "hotel5.jpg",
  "images": [
    "hotel51.jpg",
    "hotel52.jpg",
    "hotel53.jpg",
    "hotel54.jpg",
    "hotel55.jpg",
    "hotel56.jpg"
  ],
  "isPremium": false,
  "rating": 4,
  "type": "room",
  "rooms": 7,
  "maxAdults": 7,
  "price": 91935,
  "goods": [
    "Air conditioning",
    "Fridge",
    "Washer",
    "Towels"
  ],
  "author": "629dbdc5745ee4203c2f2c93",
  "countComments": 1,
  "location": {
    "latitude": 52,
    "longitude": 4
  }
}


### Удаление предложения
DELETE http://localhost:4000/offers/627b812d07347a02bbf47a44 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczJAb3Zlcmxvb2submV0IiwiaWQiOiI2MmFhZTU3Y2FiYTA4ZjU1NTQwM2JlMzYiLCJpYXQiOjE2NTU0NTE2NTcsImV4cCI6MTY1NTYyNDQ1N30.iKg5P0O0p_1jKRJ_pHL4NOSwFL-ihIcCao8xx3dw3RE


### Получение всех предложений
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json


### Получение одного предложения
GET http://localhost:4000/offers/62a1900b1a068de51bd8a34c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYyOTliZTI1NjlkNThlYzg0NjI0OTIyMyIsImlhdCI6MTY1NTI3NzE5MSwiZXhwIjoxNjU1NDQ5OTkxfQ.KPpW4ERzfN3FYD6RJFIgtNFX3tM2Lc5cyLhhxzs3LJI


### Получение премиум предложений
GET http://localhost:4000/offers/premium HTTP/1.1
Content-Type: application/json


### Получение всех комментариев по предложению
GET http://localhost:4000/offers/62b2da7fe507a241600291cc/comments HTTP/1.1
Content-Type: application/json


### Создание комментария
POST http://localhost:4000/offers/62ac48f99abde4d036d7a316/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczJAb3Zlcmxvb2submV0IiwiaWQiOiI2MmFhZTU3Y2FiYTA4ZjU1NTQwM2JlMzYiLCJpYXQiOjE2NTU0NTE2NTcsImV4cCI6MTY1NTYyNDQ1N30.iKg5P0O0p_1jKRJ_pHL4NOSwFL-ihIcCao8xx3dw3RE

{
  "text": "Текст нового комментария",
  "rating": 5
}


### Добавление предложения в избранное
POST http://localhost:4000/offers/favorites/62ba949245d8e0f46d9c30f9/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczRAb3Zlcmxvb2submV0IiwiaWQiOiI2MmJhOTNjZDQ1ZDhlMGY0NmQ5YzMwZjMiLCJpYXQiOjE2NTYzOTQ3MzAsImV4cCI6MTY1NjU2NzUzMH0.JZvaXkRdEVAW6Fj6ODeTD5S8KdQyeknwZUiyc8KZCVo


### Удаление предложения из избранного
POST http://localhost:4000/offers/favorites/62ba949245d8e0f46d9c30f9/0 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczRAb3Zlcmxvb2submV0IiwiaWQiOiI2MmJhOTNjZDQ1ZDhlMGY0NmQ5YzMwZjMiLCJpYXQiOjE2NTYzOTQ3MzAsImV4cCI6MTY1NjU2NzUzMH0.JZvaXkRdEVAW6Fj6ODeTD5S8KdQyeknwZUiyc8KZCVo


### Получение избранных предложений
GET http://localhost:4000/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczRAb3Zlcmxvb2submV0IiwiaWQiOiI2MmJhOTNjZDQ1ZDhlMGY0NmQ5YzMwZjMiLCJpYXQiOjE2NTYzOTQ3MzAsImV4cCI6MTY1NjU2NzUzMH0.JZvaXkRdEVAW6Fj6ODeTD5S8KdQyeknwZUiyc8KZCVo
